---
name: File-Find-Rule-Ext2-FileAttributes
version: 0.02
author:
  - 'Dean Wilson <dean.wilson@gmail.com> L<http://www.unixdaemon.net>'
abstract: rules to match on Ext2::FileAttributes
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  File::Find::Rule: 0
  Linux::Ext2::FileAttributes: 0
  Test::More: 0
provides:
  File::Find::Rule::Ext2::FileAttributes:
    file: lib/File/Find/Rule/Ext2/FileAttributes.pm
    version: 0.02
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
